# Playbook to Pull vSphere VM facts

- name: Get vSphere Info
  hosts: localhost

  vars:
    vm_name: myVM

  tasks:
    - name: "Get Facts about VM"
      vmware_guest_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        schema: "vsphere"
        tags: yes
        # properties: ["config.hardware.memoryMB", "guest.disk", "overallStatus"]
      delegate_to: localhost
      register: guest_facts

    - name: Return Guest Facts
      debug:
        var: guest_facts